SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

ALTER DATABASE doucka2026_videoboutique CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE category CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

UPDATE category SET nameFr = 'Électronique', icon = '📱' WHERE slug = 'electronics';
UPDATE category SET nameFr = 'Téléphones & Tablettes', icon = '🤳' WHERE slug = 'phones-tablets';
UPDATE category SET nameFr = 'Ordinateurs', icon = '💻' WHERE slug = 'computers';
UPDATE category SET nameFr = 'Accessoires', icon = '🔌' WHERE slug = 'electronics-accessories';
UPDATE category SET nameFr = 'TV & Audio', icon = '📺' WHERE slug = 'tv-audio';
UPDATE category SET nameFr = 'Mode', icon = '👕' WHERE slug = 'fashion';
UPDATE category SET nameFr = 'Vêtements Homme', icon = '🤵' WHERE slug = 'men-fashion';
UPDATE category SET nameFr = 'Vêtements Femme', icon = '👗' WHERE slug = 'women-fashion';
UPDATE category SET nameFr = 'Chaussures', icon = '👟' WHERE slug = 'shoes';
UPDATE category SET nameFr = 'Sacs & Accessoires', icon = '👜' WHERE slug = 'fashion-accessories';
UPDATE category SET nameFr = 'Véhicules', icon = '🚗' WHERE slug = 'vehicles';
UPDATE category SET nameFr = 'Voitures', icon = '🚘' WHERE slug = 'cars';
UPDATE category SET nameFr = 'Motos & Scooters', icon = '🏍️' WHERE slug = 'motorcycles';
UPDATE category SET nameFr = 'Pièces Détachées', icon = '⚙️' WHERE slug = 'vehicle-parts';
UPDATE category SET nameFr = 'Engins Lourds', icon = '🚜' WHERE slug = 'heavy-equipment';
UPDATE category SET nameFr = 'Immobilier', icon = '🏠' WHERE slug = 'real-estate';
UPDATE category SET nameFr = 'Appartements à louer', icon = '🏢' WHERE slug = 'apartments-rent';
UPDATE category SET nameFr = 'Maisons à vendre', icon = '🏡' WHERE slug = 'houses-sale';
UPDATE category SET nameFr = 'Terrains', icon = '🧱' WHERE slug = 'land';
UPDATE category SET nameFr = 'Bureaux & Commerces', icon = '🏬' WHERE slug = 'commercial';
UPDATE category SET nameFr = 'Maison', icon = '📦' WHERE slug = 'home';
UPDATE category SET nameFr = 'Meubles', icon = '🛋️' WHERE slug = 'furniture';
UPDATE category SET nameFr = 'Électroménager', icon = '🧺' WHERE slug = 'appliances';
UPDATE category SET nameFr = 'Décoration', icon = '🏺' WHERE slug = 'decoration';
UPDATE category SET nameFr = 'Jardin & Bricolage', icon = '🛠️' WHERE slug = 'garden-diy';
UPDATE category SET nameFr = 'Services', icon = '🤝' WHERE slug = 'services';
UPDATE category SET nameFr = 'Cours & Formations', icon = '📚' WHERE slug = 'training';
UPDATE category SET nameFr = 'Réparation & Travaux', icon = '🔧' WHERE slug = 'repairs';
UPDATE category SET nameFr = 'Événementiel', icon = '🎉' WHERE slug = 'events';
UPDATE category SET nameFr = 'Transport & Déménagement', icon = '🚛' WHERE slug = 'transport';
UPDATE category SET nameFr = 'Beauté & Santé', icon = '✨' WHERE slug = 'beauty-health';
UPDATE category SET nameFr = 'Cosmétiques', icon = '💄' WHERE slug = 'cosmetics';
UPDATE category SET nameFr = 'Soins du corps', icon = '🛁' WHERE slug = 'body-care';
UPDATE category SET nameFr = 'Parfums', icon = '🌹' WHERE slug = 'perfumes';
UPDATE category SET nameFr = 'Équipements médicaux', icon = '🩺' WHERE slug = 'medical-equipment';
UPDATE category SET nameFr = 'Agriculture & Alimentation', icon = '🌾' WHERE slug = 'agriculture-food';
UPDATE category SET nameFr = 'Produits Agricoles', icon = '🌽' WHERE slug = 'farm-products';
UPDATE category SET nameFr = 'Élevage', icon = '🐄' WHERE slug = 'livestock';
UPDATE category SET nameFr = 'Matériel Agricole', icon = '🚜' WHERE slug = 'farm-tools';
UPDATE category SET nameFr = 'Epicerie', icon = '🛒' WHERE slug = 'grocery';
UPDATE category SET nameFr = 'Emploi', icon = '💼' WHERE slug = 'jobs';
UPDATE category SET nameFr = 'Offres d\'emploi', icon = '✉️' WHERE slug = 'job-offers';
UPDATE category SET nameFr = 'Demandes d\'emploi', icon = '📝' WHERE slug = 'job-requests';
UPDATE category SET nameFr = 'Équipement Sportif', icon = '⚽' WHERE slug = 'sport-gear';
UPDATE category SET nameFr = 'Livres & Musique', icon = '🎸' WHERE slug = 'books-music';
UPDATE category SET nameFr = 'Autre', icon = '❔' WHERE slug = 'other';
